# Generated by Django 5.0.2 on 2024-04-12 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_chompski', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GnomeChompskiEmployee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('authorization', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'gnome_chompski_employee',
            },
        ),
        migrations.CreateModel(
            name='GnomeChompskiSwarm',
            fields=[
                ('swarm_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('quantity', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'gnome_chompski_swarm',
            },
        ),
        migrations.RemoveField(
            model_name='swarm',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='employee',
            name='authorization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='oversees',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gnome_chompski.employee'),
        ),
        migrations.AlterField(
            model_name='oversees',
            name='swarm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gnome_chompski.swarm'),
        ),
        migrations.AlterField(
            model_name='swarm',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swarm',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='oversees',
            table='oversees',
        ),
        migrations.AlterModelTable(
            name='swarm',
            table='swarm',
        ),
        migrations.CreateModel(
            name='GnomeChompskis',
            fields=[
                ('chompskis_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('no_teeth', models.PositiveIntegerField(blank=True, null=True)),
                ('swarm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gnome_chompski.swarm')),
            ],
            options={
                'db_table': 'gnome_chompskis',
            },
        ),
        migrations.CreateModel(
            name='GnomeChompskiOversees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gnome_chompski.gnomechompskiemployee')),
                ('swarm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gnome_chompski.gnomechompskiswarm')),
            ],
            options={
                'db_table': 'gnome_chompski_oversees',
            },
        ),
        migrations.CreateModel(
            name='GnomeChompskiGnomeChompskis',
            fields=[
                ('chompskis_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_teeth', models.PositiveIntegerField()),
                ('swarm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gnome_chompski.gnomechompskiswarm')),
            ],
            options={
                'db_table': 'gnome_chompski_gnome_chompskis',
            },
        ),
        migrations.DeleteModel(
            name='Gnome_Chompskis',
        ),
    ]
